### ISSUE TITLE
镜像貌似依赖不对

### ISSUE THREAD

**Issue by kehuai007** [zhaoyunxing92/docker-case#1]
PS E:\elasticsearch> docker logs 2b
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Invalid -Xlog option '-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m', see error log for details.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
[0.001s][error][logging] Error opening log file 'logs/gc.log': Permission denied
[0.001s][error][logging] Initialization of output 'file=logs/gc.log' using options 'filecount=32,filesize=64m' failed.
PS E:\elasticsearch>

**Comment by zhaoyunxing92** [comment]
抱歉，现在才看到你的问题。这个是目录权限的问题，你要设置下gc.log权限

[可能遇到的问题](https://github.com/zhaoyunxing92/docker-case/tree/develop/elasticsearch#%E5%8F%AF%E8%83%BD%E9%81%87%E5%88%B0%E7%9A%84%E9%97%AE%E9%A2%98)

**Comment by zhaoyunxing92** [comment]
还有就是你jdk的版本也有点高
